/*
 * This source file was generated by the Gradle 'init' task
 */
package Testing;

import org.junit.jupiter.api.Test;




class MessageUtilsTest {
    @Test void testGetMessage() {
        
    }
}
